# Config file for automatic testing at travis-ci.org

language: python
env:
    global:
        - DATABASE_URL="postgres://postgres@localhost:5432/travis_ci_test"
    matrix:
        - TOXENV=py27
        - TOXENV=py34
        - TOXENV=docs
        - TOXENV=flake8
        - TOXENV=coverage

install: pip install tox
before_script: psql -c 'create database travis_ci_test;' -U postgres
script: tox
